blog/urls.py
from django.urls import path
from blog import views
from blog.views import blog, create_post, edit_post, post_page, delete_post, delete_comment

urlpatterns = [
    path('', blog, name='blog'),
    path('post/new/', create_post, name='create_post'),
    path('post/<int:post_id>/edit/', edit_post, name='edit_post'),
    path('post/<int:post_id>/page/', post_page, name='post_page'),
    path('post/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('post/<int:post_id>/deactivate/', views.deactivate_post, name='deactivate_post'),
    path('comment/<int:comment_id>/delete', delete_comment, name='delete_comment'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vinme.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import CustomPasswordChangeView, complete_profile, profile_view, settings_view, change_username
from . import views

urlpatterns = [
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('complete-profile/', complete_profile, name='complete_profile'),
    path('profile/<str:username>/', profile_view, name='profile_view'),
    path('settings/', settings_view, name='settings_view'),
    path('change-username/', change_username, name='change_username'),
    ]

users/models.py
from django.db import models
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/',  null=True, blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True) 
    biography = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}'s profile"

users/forms.py
from django import forms
from allauth.account.forms import SignupForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User    
from allauth.account.forms import ChangePasswordForm
from django.utils.translation import gettext as _
from .models import UserProfile

# classe email e username
class UsernameAndEmailClean:
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Este nome de usuário já está em uso. Por favor, escolha outro.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este email já está registrado. Por favor, use outro email.")
        return email


# formulario completar usuario
class UserProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'first_name', 'last_name', 'birth_date', 'nationality', 'phone_number', 'biography']

# formulario de alterar a senha validações
class CustomPasswordChangeForm(ChangePasswordForm):
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("As senhas estão diferentes."))
        return password2
    
    def clean_oldpassword(self):
        oldpassword = self.cleaned_data.get('oldpassword')
        if not self.user.check_password(oldpassword):
            raise forms.ValidationError(_("Sua senha atual está incorreta."))
        return oldpassword
    
# formulario de cadastro validações
class CustomSignupForm(SignupForm, UsernameAndEmailClean):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
# formulario de username
class UsernameChangeForm(forms.ModelForm, UsernameAndEmailClean):
    class Meta:
        model = User
        fields = ['username']

    def __init__(self, *args, **kwargs):
        super(UsernameChangeForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
        })

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from vinme.views import pages, add_pages_context
from django.contrib import messages
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required


from allauth.account.views import PasswordChangeView
from .forms import CustomPasswordChangeForm


from users.forms import UserProfileForm
from users.models import UserProfile
from django.contrib.auth.models import User
from users.forms import UsernameChangeForm


class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm

    def form_invalid(self, form):
        if 'oldpassword' in form.errors:
            messages.error(self.request, _('Sua senha atual está incorreta.'))
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, _('Senha alterada com sucesso!'))
        return super().form_valid(form)
    


@login_required
def complete_profile(request):
    user = request.user
    user_profile, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            print("Form saved successfully")
            return redirect('profile_view', username=user.username)
        else:
            print("Form is not valid", form.errors)
    else:
        form = UserProfileForm(instance=user_profile)
    
    return render(request, 'users/complete_profile.html', {'form': form})

@login_required
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    user_profile, created = UserProfile.objects.get_or_create(user=user)
    is_own_profile = (user == request.user)

    context = {
        'profile': user_profile,
        'is_own_profile': is_own_profile
    }
    context = add_pages_context(context) 
    return render(request, 'users/profile.html', context)

@login_required
def settings_view(request):
    context = {}
    context = add_pages_context(context)
    return render(request, 'users/settings.html', context)

@login_required
def change_username(request):
    user = request.user
    user_profile, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = UsernameChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Seu nome de usuário foi atualizado com sucesso!')
            return redirect('profile_view', username=user.username)
    else:
        form = UsernameChangeForm(instance=request.user)

    return render(request, 'users/change_username.html', {'form': form})

templates/users/baseUsers.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vinme</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static '/favicon/favicon.ico' %}" type="image/x-icon">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static '/styles/styles.css' %}">
    <!-- CDN FONTE AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    {% include "vinme/partials/_preLoading.html" %}
    <div id="main-content">
        {% include 'vinme/partials/_header.html' %}
        {% block content %}

        {% endblock %}
        {% include 'allauth/layouts/partials/_footerAcc.html' %}
    </div>
    
    <!-- JAVASCRIPT -->
    <script src="{% static '/javascript/preLoader.js' %}" defer></script>

    <script src="{% static '/javascript/scrollSection.js' %}" defer></script>
    <script src="{% static '/javascript/darkmode.js' %}" defer></script>
    <script src="{% static '/javascript/animationView.js' %}" defer></script>
    <script src="{% static '/javascript/modal.js' %}" defer></script>
    <script src="{% static '/javascript/tabs.js' %}" defer></script>
    <script src="{% static '/javascript/dropdownMenu.js' %}" defer></script>
    <script src="{% static '/javascript/slider.js' %}" defer></script>
</body>
</html>

templates/users/change_username.html
{% extends "account/base_entrance.html" %}
{% load static %}

{% block content %}
<div class="account_title">
  <i class="fa-solid fa-id-card-clip"></i>
</div>

<form method="POST" class="account_form account_margin-1">
  {% csrf_token %}
  <div class="account_control">
    <input type="text" name="username" id="username" class="account_input" value="{{ form.username.value|default_if_none:'' }}" required>
    <i class="fa-solid fa-user account_icon"></i>
    <label for="username" class="account_label">Novo username</label>
    <span class="account_span"></span>
  </div>

  <div class="messages">
        {{ form.username.errors }}
  </div>

  <div class="account_row">
    <button type="submit" class="account_btn">Alterar username</button>
    <a href="{% url 'settings_view' %}" class="account_btn-1" >Cancelar</a>
  </div>
  
</form>
{% endblock %}

templates/users/complete_profile.html
{% extends "account/base_entrance.html" %}
{% load static %}

{% block content %}
<body>
    <div class="account_title">
        <i class="fa-solid fa-id-card"></i>
    </div>

    <span class="account_line"></span>
    
    <form method="post" enctype="multipart/form-data" class="account_form account_margin-1">
        {% csrf_token %}

        <div class="messages">
            <span></span>
        </div>

        <div class="account_row">
            <div class="account_menu_img">
                <img src="{% if form.instance.profile_picture %}{{ form.instance.profile_picture.url }}{% else %}{% static 'assets/img/fotografias/_unknown.png' %}{% endif %}" class="account_menu_foto" id="preview_image">
            </div>
            <input type="file" name="profile_picture" id="id_profile_picture" class="account_input" style="display: none;">
            <label for="id_profile_picture" class="account_btn">Adicionar Foto</label>
        </div>

        <div class="account_row">
            <div class="account_control">
                <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" class="account_input" value="{{ form.first_name.value }}" required>
                <i class="fa-solid fa-user-tie account_icon"></i>
                <label for="{{ form.first_name.id_for_label }}" class="account_label">Nome</label>
                <span class="account_span"></span>
            </div>
            <div class="account_control">
                <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" class="account_input" value="{{ form.last_name.value }}" required>
                <i class="fa-solid fa-user-tie account_icon"></i>
                <label for="{{ form.last_name.id_for_label }}" class="account_label">Sobrenome</label>
                <span class="account_span"></span>
            </div>
        </div>
        <div class="account_control">
            <input type="date" name="{{ form.birth_date.name }}" id="{{ form.birth_date.id_for_label }}" class="account_input" value="{{ form.birth_date.value|date:'Y-m-d' }}" required>
            <i class="fa-solid fa-calendar-days account_icon account_icon_ativo"></i>
            <label for="{{ form.birth_date.id_for_label }}" class="account_label account_label_ativo">Data de nascimento</label>
            <span class="account_span account_span_ativo"></span>
        </div>
        <div class="account_row">
            <div class="account_control">
                <input type="text" name="{{ form.nationality.name }}" id="{{ form.nationality.id_for_label }}" class="account_input" value="{{ form.nationality.value }}" required>
                <i class="fa-solid fa-earth-americas account_icon"></i>
                <label for="{{ form.nationality.id_for_label }}" class="account_label">Nacionalidade</label>
                <span class="account_span"></span>
            </div>
            <div class="account_control">
                <input type="text" name="{{ form.phone_number.name }}" id="{{ form.phone_number.id_for_label }}" class="account_input" value="{{ form.phone_number.value }}" required>
                <i class="fa-solid fa-phone account_icon"></i>
                <label for="{{ form.phone_number.id_for_label }}" class="account_label">DDD + Telefone</label>
                <span class="account_span"></span>
            </div>
        </div>
        <div class="account_control">
            <textarea name="{{ form.biography.name }}" id="{{ form.biography.id_for_label }}" class="account_input">{{ form.biography.value }}</textarea>
            <i class="fa-solid fa-comment-dots account_icon"></i>
            <label for="{{ form.biography.id_for_label }}" class="account_label">Biografia</label>
            <span class="account_span_text"></span>
        </div>
        <div class="account_row">
            <button type="submit" class="account_btn">Salvar</button>
            <a href="{% url 'profile_view' request.user.username %}" class="account_btn-1" >Cancelar</a>
        </div>
    </form>
</body>
</html>
{% endblock %}

templates/users/profile.html
{% extends "users/baseUsers.html" %}
{% load static %}

{% block content %}
<section class="container profile">
    
    <div class="profile_box">
        <!-- CONTENT -->
        <div class="profile_content">
            <!-- person -->
            <div class="profile_person">
                <!-- PERFIL -->
                <div class="profile_profile">
                    <div class="profile_img">
                        <img src="{% if profile.profile_picture %}{{ profile.profile_picture.url }}{% else %}{% static 'assets/img/fotografias/_unknown.png' %}{% endif %}" class="profile_photo">
                    </div>
                    <!-- INFOS -->
                    <div class="profile_infos">
                        <h2 class="profile_name">{{ profile.user.username }}</h2>
                        <!-- NUMBER -->
                        <div class="profile_number">
                            <span class="number_pub"></span>
                            <span class="number_follower"></span>
                            <span class="number_following"></span>
                        </div>
                    </div>
                    <!-- BUTTOn -->
                    <div class="profile_btn">
                        {% if is_own_profile %}
                            <a class="profile_button" href="{% url 'complete_profile' %}">
                                <i class="fa-solid fa-user-pen"></i>
                                <span>Editar perfil</span>
                            </a>
                            <a class="profile_button" href="{% url 'settings_view' %}">
                                <i class="fa-solid fa-gear"></i>
                                <span>Configurações</span>
                            </a>
                        {% else %}
                            <a class="profile_button" href="#">
                                <i class="fa-solid fa-user-plus"></i>
                                <span>Adicionar aos amigos</span>
                            </a>
                            <a class="profile_button">
                                <i class="fa-solid fa-ellipsis-h"></i>
                                <span>Opções</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <!-- BIO -->
                <div class="profile_bio">
                    <p>{{ profile.biography }}</p>
                </div>
            </div>
            <div class="profile_highlight">
                <div class="highlight_title">
                    <h3>Destaques</h3>
                </div>

                <div class="profile_highlight_box">

                </div>
            </div>
        </div>
    </div>
    <div class="profile_pub">
        
    </div>
    
    {% include 'allauth/layouts/partials/_footerAcc.html' %}
</section>
{% endblock %}

templates/users/settings.html
{% extends "users/baseUsers.html" %}
{% load static %}

{% block content %}
<section class="container settings">
    <div class="settings_box">
        <div class="settings_content">

            <div class="settins_title">
                <i class="fa-solid fa-gear"></i>
                <h2>Configurações</h2>
            </div>

            <div class="settings_section">
                <div class="settings_dropdown_title dropdown_close seta_dropdown">
                    <h3 class="settings_dropdown_subtitle">Conta e segurança</h3>
                    <i class="fa-solid fa-caret-down settings_dropdown_seta"></i>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Perfil</h4>
                        <a href="{% url 'complete_profile' %}" class="account_btn-1">
                            <i class="fa-solid fa-user-pen"></i>
                            <span>editar</span>
                        </a>
                    </div>
                    <div class="settings_subsection">
                        <h4>Username</h4>
                        <a href="{% url 'change_username' %}" class="account_btn-1">
                            <i class="fa-solid fa-user-pen"></i>
                            <span>editar</span>
                        </a>
                    </div>
                    <div class="settings_subsection">
                        <h4>Email</h4>
                        <a href="{% url 'account_email' %}" class="account_btn-1">
                            <i class="fa-solid fa-user-pen"></i>
                            <span>editar</span>
                        </a>
                    </div>
                    <div class="settings_subsection">
                        <h4>Senha</h4>
                        <a href="{% url 'account_change_password' %}" class="account_btn-1">
                            <i class="fa-solid fa-user-pen"></i>
                            <span>editar</span>
                        </a>
                    </div>
                </div>
            </div>


            <div class="settings_section">
                <div class="settings_dropdown_title dropdown_close seta_dropdown">
                    <h3 class="settings_dropdown_subtitle">Notificações</h3>
                    <i class="fa-solid fa-caret-down settings_dropdown_seta"></i>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Notificações por Email</h4>
                    </div>
                </div>
            </div>


            <div class="settings_section">
                <div class="settings_dropdown_title dropdown_close seta_dropdown">
                    <h3 class="settings_dropdown_subtitle">Privacidade</h3>
                    <i class="fa-solid fa-caret-down settings_dropdown_seta"></i>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Visibilidade do Perfil</h4>
                    </div>
                </div>
            </div>


            <div class="settings_section">
                <div class="settings_dropdown_title dropdown_close seta_dropdown">
                    <h3 class="settings_dropdown_subtitle">VinmeVerse</h3>
                    <i class="fa-solid fa-caret-down settings_dropdown_seta"></i>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Gerenciar postagens</h4>
                    </div>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Comentarios</h4>
                    </div>
                </div>
            </div>


            <div class="settings_section">
                   <div class="settings_dropdown_title dropdown_close seta_dropdown">
                    <h3 class="settings_dropdown_subtitle">VinmeCommunity</h3>
                    <i class="fa-solid fa-caret-down settings_dropdown_seta"></i>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Amigos</h4>
                    </div>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Grupos</h4>
                    </div>
                </div>
                <div class="settings_dropdown_content dropdown_content">
                    <div class="settings_subsection">
                        <h4>Postagens</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}